name : Mirroring

on: [push]

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
      run: |
      find -lname "#*, *#, *~, *.a, *.o, *.so, *.gcno, *.gcda, *.gcov, pain_au_chocolat"
      find name "tmp"
      echo "Unwanted file detected:"
      exit 1