name : Mirroring

on: [push]

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: find
      run: |
        file=$(find -lname "#*, *#, *~, *.a, *.o, *.so, *.gcno, *.gcda, *.gcov, pain_au_chocolat")
        dir=$(find -type d -name "tmp")
        if [ $file -gt 0] && [ $dir -gt 0]; then
          exit 1
        fi